name: Run Capture Service with Ngrok

on:
  push:
    branches:
      - master

jobs:
  run-service:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      - name: Start Capture Service
        run: |
          node capture.js &
          sleep 10 # Wait for the server to start

      - name: Install and Start Ngrok
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list >/dev/null
          sudo apt update && sudo apt install ngrok
          ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
          ngrok http 9999 > ngrok.log &
          sleep 5 # Wait for Ngrok to start

      - name: Fetch Ngrok URL
        run: |
          NGROK_URL=$(curl -s http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url')
          echo "NGROK_URL=${NGROK_URL}" >> $GITHUB_ENV

      - name: Update HTML with Ngrok URL
        run: |
          sed -i "s|Loading...|${{ env.NGROK_URL }}|g" index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
